name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["master"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rescenic
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
